const localPages = new Set([
  "/digital-pr",
  "/online-presence-management",
  "/calculator/serp-reputation-score",
  "/calculator/executive-reputation-score",
  "/calculator/crisis-response-time",
  "/calculator/brand-monitoring-roi",
  "/calculator/review-impact-revenue",
  "/calculator/reputation-recovery-timeline",
  "/calculator/reputation-damage-cost",
  "/calculator/reputation-risk-score",
  "/anti-case/how-an-ad-campaign-became-a-crisis-multiplier-during-a-stock-decline",
  "/anti-case/ses-ai-guidance-collapse",
  "/anti-case/medpace-holdings-case",
  "/anti-case/starbucks-korea-tank-day",
  "/anti-case/kpmg-australia-reputation-crisis",
  "/anti-case/targets-jay-z-moment",
  "/anti-case/kevin-oleary-ftx-reputation-collapse",
  "/anti-case/data-center-narrative-collapse-q1-2026",
  "/anti-case/keisgji1l1-intuits-narrative-gap-how-overpromised-g",
  "/anti-case/ai-chatbot-pr-risk-chevrolet",
  "/anti-case/cracker-barrel-rebrand-crisis",
  "/anti-case/rackspace-ai-narrative-collapse",
  "/anti-case/meta-india-content-decision-safe-harbor-risk",
  "/case-study-executive-profile-rebuild",
  "/case-study-founder-distancing",
  "/case-study-executive-exit-search",
  "/case-study-narrative-redirection",
  "/case-study-public-figure-serm",
  "/case-study-footprint-kyc",
  "/case-study-serm-multiregion",
  "/case-study-kenya",
  "/news",
  "/blog",
  "/risk-calculator",
  "/sitemap_html",
  "/cookies-policy",
  "/privacy-policy",
  "/cis-market-entry-strategy",
  "/china-market-entry-strategy",
  "/ai-digital-reputation-protection",
  "/reputation-audit",
  "/remove-negative-content",
  "/reputation-services-for-individuals",
  "/reputation-services-for-companies",
  "/",
  "/solutions",
  "/reputation-management-pricing",
  "/faq",
  "/contacts",
  "/risk-control-center",
  "/company",
  "/case-studies",
  "/rh-detection",
  "/rh-control",
  "/rh-defence",
  "/rh-personal",
  "/team",
  "/online-reputation-monitoring",
  "/social-listening",
  "/brand-audit",
  "/ai-brand-monitoring",
  "/digital-risk-protection",
  "/brand-reputation-services",
  "/serm-services",
  "/online-review-management",
  "/ai-influence-services",
  "/brand-positioning-services",
  "/brand-launch-strategy",
  "/employer-reputation-management",
  "/brand-protection-services",
  "/online-reputation-repair",
  "/crisis-management-agency",
  "/business-media-presence",
  "/personal-reputation-crisis",
  "/personal-reputation-repair",
  "/public-figure-reputation-management",
  "/personal-reputation-building",
  "/personal-reputation-monitoring",
  "/personal-online-reputation",
]);

export function resolveSiteLink(href: string) {
  const value = href.trim();
  if (value === "/cases-hub" || value === "https://reputation.house/cases-hub")
    return "/case-studies";
  if (!value.startsWith("https://reputation.house")) return value;
  const url = new URL(value);
  const path = url.pathname.replace(/\/$/, "") || "/";
  return url.hostname === "reputation.house" && localPages.has(path)
    ? `${path}${url.search}${url.hash}`
    : value;
}
