import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const base = process.env.NUXT_APP_BASE_URL || '/rh-site/';
if (!/^\/(?:[^?#\\]+\/)?$/.test(base)) throw new Error('Base URL must start and end with /');
const result = spawnSync(process.execPath, ['node_modules/@nuxt/cli/bin/nuxi.mjs', 'generate'], {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, PAGES_BUILD: '1', NUXT_APP_BASE_URL: base },
});
if (result.status !== 0) process.exit(result.status || 1);

const output = path.join(root, '.pages', 'public');
const destination = path.join(root, 'docs');
if (!fs.existsSync(path.join(output, 'index.html'))) throw new Error('Missing generated index.html');
// docs is exclusively generated output. Refuse to replace an unrelated directory.
const marker = path.join(destination, '.pages-generated');
if (fs.existsSync(destination) && !fs.existsSync(marker)) throw new Error('docs exists without the generated-output marker');
if (path.dirname(destination) !== root) throw new Error('Output must remain inside this project');
fs.rmSync(destination, { recursive: true, force: true });
fs.cpSync(output, destination, { recursive: true });
fs.writeFileSync(marker, `Generated by npm run build:pages\nBase URL: ${base}\n`);
fs.writeFileSync(path.join(destination, '.nojekyll'), '');
// Files copied directly from public bypass Vite.
for (const file of fs.readdirSync(destination, { recursive: true }).filter(f => f.endsWith('.css'))) {
  const target = path.join(destination, file);
  const source = fs.readFileSync(target, 'utf8');
  fs.writeFileSync(target, source.replace(/(url\(\s*["']?)\/(images|fonts|styles)\//g, `$1${base}$2/`));
}
const check = spawnSync(process.execPath, ['scripts/verify-pages.mjs'], {
  cwd: root, stdio: 'inherit', env: { ...process.env, NUXT_APP_BASE_URL: base },
});
process.exit(check.status ?? 1);
